image: openjdk:16
stages:
  - build
  - test

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean
    - mvn compile
  artifacts:
    paths:
      - target/comma_counter_-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script:
    - mvn clean test